// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bshtnthuzotuytyeoovd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzaHRudGh1em90dXl0eWVvb3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjM5MDcsImV4cCI6MjA2MDQ5OTkwN30.eoj_F5KV8x9Fup7enMgcq3iLDyCD1nTiYY5x3T8haqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);